development:
  host: localhost
  adapter: mysql
  reconnect: false
  database: crm_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  host: localhost
  adapter: mysql
  reconnect: false
  database: crm_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  host: localhost
  adapter: mysql
  reconnect: false
  database: crm_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
